name = "Celeumu"
license = "MIT"
licenselink = ""
description = ""
homepage = ""
tags = [
  "blog",
  "minimal",
  "minimalist",
  "responsive"
]
features = [
  "accessibility",
  "analytics",
  "comments",
  "cover-image",
  "favicon",
  "multilingual",
  "opengraph",
  "pagination",
  "shortcodes",
  "single-column",
  "social-menu",
  "syntax-highlighting",
]
min_version = 0.01

pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsCodefencesGuessSyntax = true

[author]
  name = "takakd"
  homepage = "https://takakd.github.io"

[original]
  name = "Kiss"
  homepage = "https://www.ribice.ba/hugo-kiss/"
  repo = "https://github.com/ribice/kiss"
  
[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ""
lineAnchors = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = "monokai"
tabWidth = 4
